//! Nerd Font icon constants used throughout the UI.

pub const ICON_DIGGER: &str = "\u{f0ad}";        // nf-fa-wrench
pub const ICON_OVERVIEW: &str = "\u{f0e4}";      // nf-fa-tachometer
pub const ICON_PROCESSES: &str = "\u{f085}";     // nf-fa-cogs
pub const ICON_HISTORY: &str = "\u{f1da}";       // nf-fa-history
pub const ICON_CPU: &str = "\u{f2db}";           // nf-fa-microchip
pub const ICON_MEMORY: &str = "\u{f538}";        // nf-fa-memory
pub const ICON_NETWORK: &str = "\u{f0ac}";       // nf-fa-globe
pub const ICON_DISK: &str = "\u{f0a0}";          // nf-fa-hdd-o
pub const ICON_TEMP: &str = "\u{f2c9}";          // nf-fa-thermometer-half
pub const ICON_SEARCH: &str = "\u{f002}";        // nf-fa-search
pub const ICON_BARS: &str = "\u{f0c9}";          // nf-fa-bars
pub const ICON_LIST: &str = "\u{f0ae}";          // nf-fa-tasks
pub const ICON_CLOCK: &str = "\u{f017}";         // nf-fa-clock-o
pub const ICON_APPS: &str = "\u{f108}";          // nf-fa-desktop
pub const ICON_BACKGROUND: &str = "\u{f0e8}";    // nf-fa-sitemap
pub const ICON_SYSTEM: &str = "\u{f013}";        // nf-fa-gear
pub const ICON_USB: &str = "\u{f287}";           // nf-fa-usb
pub const ICON_LOADING: &str = "\u{f254}";       // nf-fa-hourglass-2
pub const ICON_ARROW_DOWN: &str = "\u{f063}";    // nf-fa-arrow-down
pub const ICON_ARROW_UP: &str = "\u{f062}";      // nf-fa-arrow-up
pub const ICON_SORT_UP: &str = "\u{f0de}";       // nf-fa-sort-asc
pub const ICON_SORT_DOWN: &str = "\u{f0dd}";     // nf-fa-sort-desc
pub const ICON_CLOSE: &str = "\u{f00d}";         // nf-fa-times
pub const ICON_SETTINGS: &str = "\u{f013}";      // nf-fa-gear
pub const ICON_PAINT: &str = "\u{f1fc}";         // nf-fa-paint-brush
pub const ICON_ACCESS: &str = "\u{f29a}";        // nf-fa-universal-access
pub const ICON_INFO: &str = "\u{f05a}";          // nf-fa-info-circle
pub const ICON_TOGGLE_ON: &str = "\u{f205}";     // nf-fa-toggle-on
pub const ICON_TOGGLE_OFF: &str = "\u{f204}";    // nf-fa-toggle-off
pub const ICON_CHECK: &str = "\u{f00c}";         // nf-fa-check
pub const ICON_CHEVRON_RIGHT: &str = "\u{f054}"; // nf-fa-chevron-right
pub const ICON_CHEVRON_DOWN: &str = "\u{f078}";  // nf-fa-chevron-down
pub const ICON_SEPARATOR: &str = "\u{2502}";     // box-drawing vertical
pub const ICON_DASH: &str = "\u{2500}";          // box-drawing horizontal
pub const ICON_BULLET: &str = "\u{2022}";        // bullet
pub const ICON_EXPORT: &str = "\u{f019}";        // nf-fa-download
pub const ICON_WARNING: &str = "\u{f071}";       // nf-fa-exclamation-triangle
pub const ICON_KILL: &str = "\u{f00d}";          // nf-fa-times (reuse)
pub const ICON_HEART: &str = "\u{f004}";         // nf-fa-heart
pub const ICON_BOLT: &str = "\u{f0e7}";          // nf-fa-bolt
pub const ICON_THREAD: &str = "\u{f126}";        // nf-fa-code-fork
pub const ICON_LOG: &str = "\u{f0ca}";           // nf-fa-list-ul
pub const ICON_LOAD: &str = "\u{f080}";          // nf-fa-bar-chart
pub const ICON_GPU: &str = "\u{f26c}";           // nf-fa-tv (GPU display)
